development:
  adapter: postgresql
  database: dev_culturalgps_app
  pool: 5
  timeout: 5000
  username: admin
  password:
  host: localhost

test:
  adapter: postgresql
  database: test_culturalgps_app
  pool: 5
  timeout: 5000
  username: admin
  password:
  host: localhost

production:
  adapter: postgresql
  database: prod_culturalgps_app
  pool: 5
  timeout: 5000
  username: admin
  password:
  host: localhost
